### ISSUE TITLE
[1.12.2] More colors maybe?

### ISSUE THREAD

**Issue by fkrisi11** [hypherionmc/hyperlighting_public#1]
I think it would be nice to have everything that is dyeable, in all vanilla dye colors.

**Comment by hypherionmc** [comment]
Thank you for your suggestion. Will definitely add this in the next version

**Comment by fkrisi11** [comment]
Nice job ^^
Thank you.

**Comment by hypherionmc** [comment]
Only a pleasure. If you have any other suggestions, you are welcome to make them. You will be credited for each suggestion implemented

**Comment by fkrisi11** [comment]
I see. That's rather nice ^^
Did you name the blocks individually that are placed in the world?
Or at least.. is there a block state difference between them, to see what color they are and if they are on or off?

I would like to add support for colored lights in my modpack, to HyperLighting, via a Json, using the Colored Lux mod. That's why I asked about the blockstates and proper block names

**Comment by hypherionmc** [comment]
At the moment each of the candles uses a different model for their On state (the next update will just replace the textures), but they all do have individual names.

And yes all of the torches and lanterns use a blockstate to check if they are turned on or not.

What information would you need from me to add it to your modpack?

**Comment by fkrisi11** [comment]
Nothing else really.
I just wanted to know about the blockstates and the block names.

And well.. don't hope for much, the modpack is.. not popular, just something me and my friends play.
But I do love the concept of atmospheric, colored lighting, so I love your mod ^^

**Comment by hypherionmc** [comment]
Well, I can create a wiki page with all the block states and block names. That should help you out.

Just for basic info, all the blocks use a facing and powered state (facing being UP, WEST, EAST, NORTH, SOUTH) and powered being (true, false). As for the block names, they all exist under the domain `hmctt`

**Comment by fkrisi11** [comment]
Oh... thanks for all the info ^^
I can check all of this in the game, but this is helpful indeed.
I feel like your mod will work well with Colored Lux

**Comment by hypherionmc** [comment]
Do send some screenshots. Will love to see how it turns out

**Comment by fkrisi11** [comment]
Until I implement that mod, take a look at this:

![pic](https://user-images.githubusercontent.com/26310365/79371029-fc4ae000-7f53-11ea-9c63-6500d8e2d78d.jpg)

I will try to use HyperLighting in a similar fashion

**Comment by hypherionmc** [comment]
I really love the flames on those

**Comment by hypherionmc** [comment]
So I made contact with the author of Colored Lux, and v1.1 will support Colored Lux out of the bag

**Comment by fkrisi11** [comment]
That's awesome ^^

**Comment by hypherionmc** [comment]
Hey. v1.1 is now out. Supports more colors and Colored Lux

**Comment by fkrisi11** [comment]
Thank you for telling me ^^
I'll include it in the next update
