### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NordicGamerFE** [hypherionmc/hyperlighting_public#3]
Hey fellow ATLauncher modpack maker here just wanted to bring this to you
![image](https://user-images.githubusercontent.com/18188155/86504117-4609d080-bdb5-11ea-979f-f3e75a76e1fa.png)

Sincerely Kevin

**Comment by Mysticpasta1** [comment]
Is this by an chance from the mystic's cubic chunks modpack

**Comment by NordicGamerFE** [comment]
Yes

**Comment by Mysticpasta1** [comment]
It looks like it needs a custom description thanks for bring this to my attention

**Comment by NordicGamerFE** [comment]
<mod name="ColorfulWater" description="I saw a mod attempt this recently, but came up short. So, this is my version of the colored water idea." Authors="BillyGalbreath" version="1.12.2-b37" url="packs/OceanOutlastExpert/files/mods/ColoredWater-1.12.2-b37.jar" file="ColoredWater-1.12.2-b37.jar" md5="e42737922592cf24eb2257655287caa8" download="server" type="mods" />

**Comment by NordicGamerFE** [comment]
[Color.txt](https://github.com/hypherionmc/hyperlighting_public/files/4872047/Color.txt)

**Comment by NordicGamerFE** [comment]
i added a capaital a by mistake in authors

**Comment by Mysticpasta1** [comment]
thanks
