### ISSUE TITLE
[FEATURE-REQUEST] [1.12.2] Config option to disable manually turning on torches, lanterns and candles

### ISSUE THREAD

**Issue by CalaMariGold** [hypherionmc/hyperlighting_public#5]
**Is your feature request related to a problem? Please describe.**
Turning on torches using a very specific item won't fit in my modpack. We use the vanilla torches as well as other light sources, all of which are on by default. 

**Describe the solution you'd like**
A config option to disable manually turning on torches, tiki torches, lanterns, and candles. All of these would be lit automatically when placed like vanilla torches.

**Describe alternatives you've considered**
A config option of a list of items that would be valid to turn on any of the lights.

**Comment by hypherionmc** [comment]
Hi. Sure shouldn't be an issue. I will add an option so that they are on by default, but can still be turned on and off like normal.

For now it will be in the latest dev build until released :)

**Comment by CalaMariGold** [comment]
Awesome! Oh, also forgot to add campfires to that list :)

**Comment by hypherionmc** [comment]
Your suggestion has been implemented. Hyper Lighting now includes two new config options for most lights. One to disable the tool requirement (so you can simply right click to activate/deactivate them) and one to have them turned on by default when placed. 

You can test it out here and it will be included in the next release: https://ci.hypherionmc.me/job/Hyper-Lighting/job/1.12.2/31/
