### ISSUE TITLE
[BUG] Crash when shift + left-clicking item in inventory

### ISSUE THREAD

**Issue by CalaMariGold** [hypherionmc/hyperlighting_public#6]
**Describe the bug**
When shift + left-clicking in your inventory to quickly move any item from the mod, a crash occurs.

**To Reproduce**
Read above

**Expected behavior**
No crash

**System (please complete the following information):**
 - OS: Win 10
 - Java Version: 1.8.0_261
 - Minecraft Version: 1.12.2
 - Forge Version: 14.23.5.2854
 - Mod Version (BE SPECIFIC. DO NOT USE LATEST!): 1.3

**Crash Report*
https://pastebin.com/zFNJKJWX

**Comment by hypherionmc** [comment]
Hi. Oh wow that's a weird one. Let me see if we can reproduce it

**Comment by CalaMariGold** [comment]
I've determined that you don't have to click. Just hover over an item (I tested it on the camp fire) and hold down shift. I suspect it's an issue with a tooltip.

**Comment by hypherionmc** [comment]
Hmmm yeah I see the crash was caused by the campfire. Could either be A) The tooltip or B) A very old bug that got fixed that I may have reintroduced in the campfires

**Comment by CalaMariGold** [comment]
Affected items: 
Both campfires
Soulfire torch
Soulfire Lantern
Both Jack O Lantern trios
Fog Machine

When hovering over in JEI:
![image](https://user-images.githubusercontent.com/57605926/94526856-24798300-0204-11eb-86e4-87c6f92b7a56.png)

**Comment by hypherionmc** [comment]
Hmm would you mind sending me your debug.log please. I never noticed that issue so might be with the newer JEI that something broke

**Comment by hypherionmc** [comment]
(Side note, just checked out your website. Your pack looks awesome!)

**Comment by CalaMariGold** [comment]
I assume you mean latest.log?

(can't upload here or use pastebin, wayyyy too big)
https://drive.google.com/file/d/1L3Sxs93UxgskvEMuEK1LqFuYjbVc35ID/view?usp=sharing

And thank you!

**Comment by hypherionmc** [comment]
Thank you, I think I know now what causes the issue. Will ask the testers to confirm my theory lol

**Comment by ADragonROAR** [comment]
Uhm I am unable to reproduce the bug if it's just Hyperlighting alone so I suspect its some mod interfering, I'll try to reproduce it with JEI and optifine but if still then I can't get this bug to appear, it's 1 of the other mods causing it. and to find it, we'll need more info (like the mod list)

**Comment by ADragonROAR** [comment]
I'm sorry but it seems to be a compat issue between Hypherligting and one (or possibly more) of the other mods u have in the pack ur playing. Wich makes it harder to track the issue.

**Comment by CalaMariGold** [comment]
"Suspected Mods: FoamFix (foamfix), Hyper Lighting (hmctt), Tool Progression (toolprogression), LagGoggles (laggoggles)"

Try reproducing it with all those mods.

**Comment by hypherionmc** [comment]
I have found the causing mod: Tool Progression. I will try and add a fix for it. As for the JEI issue, I cannot reproduce that at all

**Comment by hypherionmc** [comment]
This issue has now been fixed (as far as I can tell). It's included in the latest dev build and will be included in release. If it's still present, please let me know

**Comment by CalaMariGold** [comment]
Thank you so much for looking into all my suggestions and fixing these issues. People playing Rebirth of the Night are going to loooove this mod!

**Comment by hypherionmc** [comment]
No problem and thank you for reporting/suggesting them. Also I noted on your discord you noticed the bug in the fog machine, that is also fixed in the latest dev
