### ISSUE TITLE
[BUG] Campfire not getting put out by rain

### ISSUE THREAD

**Issue by CalaMariGold** [hypherionmc/hyperlighting_public#7]
**Describe the bug**
The campfire isn't getting put out by the rain like the tooltip said it should.

**To Reproduce**
Place a lit campfire exposed to the sky while raining

**Expected behavior**
Campfire should be put out when it starts raining (or a few seconds after)

**Screenshots**
![image](https://user-images.githubusercontent.com/57605926/94527354-d618b400-0204-11eb-81f4-dcd802dd8855.png)

**System (please complete the following information):**
OS: Win 10
Java Version: 1.8.0_261
Minecraft Version: 1.12.2
Forge Version: 14.23.5.2854
Mod Version (BE SPECIFIC. DO NOT USE LATEST!): 1.3

**Comment by hypherionmc** [comment]
Jikes when did I break that? Is this server or single player?

**Comment by hypherionmc** [comment]
And you don't have something that modifies the random tick rate by any chance?

**Comment by CalaMariGold** [comment]
Singleplayer. And no, I don't believe we're modifying random tick rate. I can't think of anything that would change that, at least.

**Comment by hypherionmc** [comment]
This issue has been fixed. The rain handling code somehow got lost between commits. It is included in the latest dev build and will be included in the release
