### ISSUE TITLE
[FEATURE-REQUEST] [1.12.2] Campfire should damage the player when standing on top

### ISSUE THREAD

**Issue by CalaMariGold** [hypherionmc/hyperlighting_public#8]
Players should take fire damage while standing on top of a campfire (like the vanilla campfire). Currently, they take no damage.

Also, a small thing I noticed is that jumping or walking on top of a campfire does not have any sound effect. It should sound like walking on top of wood planks.

**Comment by hypherionmc** [comment]
Ah, knew I forgot something. Would you be cool with testing a dev build? I will try to resolve all the issues and add the features after work tonight. Thank you for actually taking the time to report them (Can't fix stuff you don't know about lol) :)

**Comment by hypherionmc** [comment]
Question, should it just damage the player or set them on fire to make it more realistic?

**Comment by CalaMariGold** [comment]
No problem! The vanilla campfire just damages, but it would be more realistic if they're on fire for a few seconds.

**Comment by hypherionmc** [comment]
Both suggestions have been implemented. The soul fire torch does however not light entities on fire due to the way it was coded to work underwater. I will implement it in the version 2.0 rewrite
