### ISSUE TITLE
[BUG] 1.0.4

### ISSUE THREAD

**Issue by SteamgoatsZora** [hypherionmc/hyperlighting_public#9]
Crash on start

might be a id issue? crash log werent helpful

**Expected behavior**
?

**System (please complete the following information):**
 - Win 10]
 - Java Version: ? 
 - Minecraft Version: 1.12
 - Forge Version: 
 - Mod Version (BE SPECIFIC. DO NOT USE LATEST!):
 - Single Player/Server:

**Crash Report*

**Comment by SteamgoatsZora** [comment]
hope the file uploaded once atleast i can repost otherwise

1.0.5 seems to be working so far

also have 10g allocated

**Comment by hypherionmc** [comment]
1.0.4 sounds like a dev build, since there is no 1.0.4 release.

Can you provide me with the crash report please

**Comment by SteamgoatsZora** [comment]
unsure where they went but it was a version endding with a 4 updated to a version ending with a 5 now 
i dragged them to last message and they arent in my folderanymore somehow
cant see as atl is closed and im loading pack il  update when load is done  sorry =)

**Comment by SteamgoatsZora** [comment]
but this version 1.0.5 works

**Comment by hypherionmc** [comment]
Hmmm, well hyper lighting ends at 1.4, so I'm not sure what release/mod this should be

**Comment by SteamgoatsZora** [comment]
at my first message it said file uploaded you sure you ddint get the log from it?

**Comment by hypherionmc** [comment]
Nope, nothing attached
![image](https://user-images.githubusercontent.com/63595580/107558669-beeec780-6be3-11eb-8f70-b0d19e03500b.png)

**Comment by SteamgoatsZora** [comment]
wierd
and files gone and not in trashbin
oh well it works no so guess its ok
but if i find them il send em

**Comment by SteamgoatsZora** [comment]
in atl launcher version is 1.0.5 now (just updated from 1.0.4) 
if that helps

**Comment by SteamgoatsZora** [comment]
yeah now theres no 1.0.4 version in atl no idea how i got it, pack were listed   must been an atl bug :) and thats explains the crash if pack werent done that version
